;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.ContinueCombo.End",DevComment="")
+GameplayTagList=(Tag="Event.ContinueCombo.Start",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.AxeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.AxeAttack.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.WeaponAbility",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shield.Bubble",DevComment="")
+GameplayTagList=(Tag="Item.Stat.Armor",DevComment="")
+GameplayTagList=(Tag="Item.Stat.AttackSpeed",DevComment="")
+GameplayTagList=(Tag="Item.Stat.Capacity",DevComment="")
+GameplayTagList=(Tag="Item.Stat.Durability",DevComment="")
+GameplayTagList=(Tag="Item.Stat.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="Item.Stat.Strength",DevComment="")
+GameplayTagList=(Tag="Item.Stat.UsesLeft",DevComment="")
+GameplayTagList=(Tag="State.Death",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Shield",DevComment="")

